-- =============================================================================
-- Talleres Ruiz · Script de Instalación Completo para Supabase
-- Ejecuta este script en el SQL Editor de tu proyecto de Supabase.
-- =============================================================================

create extension if not exists pgcrypto;

-- 1. Secuencias
create sequence if not exists public.orden_numero start with 1000;
create sequence if not exists public.visitante_web start with 1;

-- 2. Tablas públicas
create table if not exists public.personas (
  id text primary key check (id ~ '^[a-z]{2,30}$'),
  nombre text not null,
  nombre_completo text not null,
  rol text not null check (rol in ('dueno', 'recepcion', 'mecanico')),
  rol_etiqueta text not null
);

create table if not exists public.clientes (
  id text primary key check (length(id) between 1 and 60),
  nombre text not null check (length(btrim(nombre)) between 1 and 200),
  nombre_corto text not null check (length(nombre_corto) between 1 and 200),
  contacto text check (length(contacto) <= 200),
  telefono text not null default '' check (length(telefono) <= 60),
  email text not null default '' check (length(email) <= 200),
  desde int not null check (desde between 1900 and 2200),
  creado timestamptz not null default now()
);

create table if not exists public.coches (
  id text primary key check (length(id) between 1 and 60),
  cliente_id text not null references public.clientes (id) on update cascade on delete restrict,
  matricula text not null check (length(btrim(matricula)) between 4 and 20),
  matricula_clave text generated always as (upper(regexp_replace(matricula, '[\s-]', '', 'g'))) stored,
  modelo text not null check (length(btrim(modelo)) between 1 and 200),
  anio int check (anio between 1950 and 2200),
  combustible text not null default 'Gasolina' check (length(combustible) <= 40),
  creado timestamptz not null default now(),
  constraint coches_matricula_unica unique (matricula_clave)
);
create index if not exists coches_cliente_idx on public.coches (cliente_id);

create table if not exists public.tarifa (
  id text primary key check (length(id) between 1 and 60),
  categoria text not null check (length(btrim(categoria)) between 1 and 100),
  nombre text not null check (length(btrim(nombre)) between 1 and 200),
  tiempo text not null default '' check (length(tiempo) <= 60),
  precio numeric(10, 2) not null check (precio between 0 and 100000),
  por_unidad boolean not null default false,
  posicion int generated by default as identity
);

create table if not exists public.ordenes (
  id text primary key default ('OT-' || nextval('public.orden_numero')),
  coche_id text not null references public.coches (id) on update cascade on delete restrict,
  estado text not null default 'recibido'
    check (estado in ('recibido', 'diagnostico', 'pieza', 'reparacion', 'listo', 'entregado')),
  km int not null check (km between 0 and 3000000),
  mecanico_id text not null references public.personas (id),
  entrada timestamptz not null default now(),
  cierre timestamptz,
  motivo text not null check (length(btrim(motivo)) between 1 and 2000),
  trabajos jsonb not null default '[]' check (jsonb_typeof(trabajos) = 'array'),
  piezas jsonb not null default '[]' check (jsonb_typeof(piezas) = 'array'),
  observaciones jsonb not null default '[]' check (jsonb_typeof(observaciones) = 'array'),
  historial jsonb not null default '[]' check (jsonb_typeof(historial) = 'array'),
  ultima_ia jsonb check (ultima_ia is null or jsonb_typeof(ultima_ia) = 'object'),
  informes jsonb not null default '{}' check (jsonb_typeof(informes) = 'object'),
  version int not null default 1,
  constraint ordenes_cierre_coherente check ((estado = 'entregado') = (cierre is not null))
);
create unique index if not exists ordenes_una_abierta_por_coche on public.ordenes (coche_id) where estado <> 'entregado';
create index if not exists ordenes_coche_idx on public.ordenes (coche_id);
create index if not exists ordenes_mecanico_abiertas_idx on public.ordenes (mecanico_id) where estado <> 'entregado';

create table if not exists public.conversaciones (
  id text primary key check (length(id) between 1 and 60),
  cliente_id text references public.clientes (id) on update cascade on delete set null,
  nombre text not null default '' check (length(nombre) <= 200),
  canal text not null check (canal in ('WhatsApp', 'Email', 'Web')),
  contacto text check (length(contacto) <= 200),
  modo text not null default 'ia' check (modo in ('ia', 'persona')),
  necesita_persona boolean not null default false,
  motivo text check (length(motivo) <= 300),
  ia_pensando_desde timestamptz,
  actualizada timestamptz not null default now(),
  creada timestamptz not null default now(),
  prueba boolean not null default false
);
create index if not exists conversaciones_cliente_idx on public.conversaciones (cliente_id);
create index if not exists conversaciones_bandeja_idx on public.conversaciones (necesita_persona desc, actualizada desc);

create table if not exists public.mensajes (
  n bigint generated always as identity,
  id text primary key check (length(id) between 1 and 60),
  conversacion_id text not null references public.conversaciones (id) on update cascade on delete cascade,
  de text not null check (de in ('cliente', 'ia', 'persona')),
  texto text not null check (length(texto) between 1 and 4000),
  cuando timestamptz not null default now(),
  autor text check (length(autor) <= 100)
);
create index if not exists mensajes_conversacion_idx on public.mensajes (conversacion_id, n);

create table if not exists public.citas (
  id text primary key check (length(id) between 1 and 60),
  fecha date not null,
  hora text not null check (hora ~ '^\d{2}:\d{2}$'),
  nombre text not null check (length(btrim(nombre)) between 1 and 200),
  telefono text not null default '' check (length(telefono) <= 60),
  matricula text not null check (length(btrim(matricula)) between 1 and 20),
  coche text not null default '—' check (length(coche) <= 200),
  motivo text not null default 'Sin especificar' check (length(motivo) <= 2000),
  cliente_id text references public.clientes (id) on update cascade on delete set null,
  orden_id text references public.ordenes (id) on update cascade on delete set null,
  conversacion_id text references public.conversaciones (id) on update cascade on delete set null,
  origen text not null check (origen in ('taller', 'ia')),
  creada timestamptz not null default now(),
  constraint citas_hueco_unico unique (fecha, hora)
);
create index if not exists citas_cliente_idx on public.citas (cliente_id);
create index if not exists citas_orden_idx on public.citas (orden_id);
create index if not exists citas_conversacion_idx on public.citas (conversacion_id);

create table if not exists public.ajustes (
  clave text primary key check (length(clave) between 1 and 60),
  valor jsonb not null default '{}'::jsonb,
  actualizado timestamptz not null default now()
);


-- 3. Esquema privado y funciones auxiliares
create schema if not exists privado;
revoke all on schema privado from public;
grant usage on schema privado to authenticated;

create or replace function privado.rol() returns text
language sql stable set search_path = '' as $$
  select coalesce((select auth.jwt()) -> 'app_metadata' ->> 'rol', '')
$$;

create or replace function privado.persona() returns text
language sql stable set search_path = '' as $$
  select coalesce((select auth.jwt()) -> 'app_metadata' ->> 'persona', '')
$$;

create or replace function privado.es_taller() returns boolean
language sql stable set search_path = '' as $$
  select privado.rol() in ('dueno', 'recepcion')
$$;

create or replace function privado.cargando() returns boolean
language sql stable set search_path = '' as $$
  select coalesce(current_setting('taller.cargando', true), '') = 'si'
$$;

-- 4. Permisos básicos y RLS
revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

grant select, insert, update, delete on public.personas to authenticated;
grant select, insert, update on public.clientes to authenticated;
grant select, insert, update on public.coches to authenticated;
grant select, insert, update, delete on public.tarifa to authenticated;
grant select, insert, update on public.ordenes to authenticated;
grant select, insert, update on public.conversaciones to authenticated;
grant select, insert on public.mensajes to authenticated;
grant select, insert, update, delete on public.citas to authenticated;
grant select, insert, update on public.ajustes to authenticated;
grant usage on sequence public.orden_numero to authenticated;

alter table public.personas enable row level security;
alter table public.clientes enable row level security;
alter table public.coches enable row level security;
alter table public.tarifa enable row level security;
alter table public.ordenes enable row level security;
alter table public.conversaciones enable row level security;
alter table public.mensajes enable row level security;
alter table public.citas enable row level security;
alter table public.ajustes enable row level security;

-- 5. Reglas de seguridad (RLS)
drop policy if exists "ajustes: taller lee y cambia" on public.ajustes;
create policy "ajustes: todos con rol leen" on public.ajustes for select to authenticated
  using ((select privado.rol()) <> '');
create policy "ajustes: taller cambia" on public.ajustes for all to authenticated
  using ((select privado.es_taller())) with check ((select privado.es_taller()));

drop policy if exists "personas: las ve el equipo" on public.personas;
drop policy if exists "personas: todos con rol leen" on public.personas;
create policy "personas: todos con rol leen" on public.personas for select to authenticated
  using ((select privado.rol()) <> '');

drop policy if exists "personas: dueño puede modificar" on public.personas;
drop policy if exists "personas: dueño inserta" on public.personas;
create policy "personas: dueño inserta" on public.personas for insert to authenticated
  with check ((select privado.rol()) = 'dueno');

drop policy if exists "personas: dueño modifica" on public.personas;
create policy "personas: dueño modifica" on public.personas for update to authenticated
  using ((select privado.rol()) = 'dueno')
  with check ((select privado.rol()) = 'dueno');

drop policy if exists "personas: dueño borra" on public.personas;
create policy "personas: dueño borra" on public.personas for delete to authenticated
  using ((select privado.rol()) = 'dueno' and id <> 'paco');

drop policy if exists "clientes: taller, y el mecanico los de sus coches" on public.clientes;
create policy "clientes: taller, y el mecanico los de sus coches" on public.clientes for select to authenticated
  using (
    (select privado.es_taller())
    or (
      (select privado.rol()) = 'mecanico'
      and exists (
        select 1 from public.coches c join public.ordenes o on o.coche_id = c.id
        where c.cliente_id = clientes.id and o.mecanico_id = (select privado.persona()) and o.estado <> 'entregado'
      )
    )
  );

drop policy if exists "clientes: taller crea" on public.clientes;
create policy "clientes: taller crea" on public.clientes for insert to authenticated
  with check ((select privado.es_taller()));

drop policy if exists "clientes: taller cambia" on public.clientes;
create policy "clientes: taller cambia" on public.clientes for update to authenticated
  using ((select privado.es_taller())) with check ((select privado.es_taller()));

drop policy if exists "coches: taller, y el mecanico los suyos" on public.coches;
create policy "coches: taller, y el mecanico los suyos" on public.coches for select to authenticated
  using (
    (select privado.es_taller())
    or (
      (select privado.rol()) = 'mecanico'
      and exists (
        select 1 from public.ordenes o
        where o.coche_id = coches.id and o.mecanico_id = (select privado.persona()) and o.estado <> 'entregado'
      )
    )
  );

drop policy if exists "coches: taller crea" on public.coches;
create policy "coches: taller crea" on public.coches for insert to authenticated
  with check ((select privado.es_taller()));

drop policy if exists "coches: taller cambia" on public.coches;
create policy "coches: taller cambia" on public.coches for update to authenticated
  using ((select privado.es_taller())) with check ((select privado.es_taller()));

drop policy if exists "tarifa: la ven todos los usuarios con rol" on public.tarifa;
create policy "tarifa: la ven todos los usuarios con rol" on public.tarifa for select to authenticated
  using ((select privado.rol()) in ('dueno', 'recepcion', 'mecanico', 'asistente'));

drop policy if exists "tarifa: el dueno crea" on public.tarifa;
create policy "tarifa: el dueno crea" on public.tarifa for insert to authenticated
  with check ((select privado.rol()) = 'dueno');

drop policy if exists "tarifa: el dueno cambia" on public.tarifa;
create policy "tarifa: el dueno cambia" on public.tarifa for update to authenticated
  using ((select privado.rol()) = 'dueno') with check ((select privado.rol()) = 'dueno');

drop policy if exists "tarifa: el dueno borra" on public.tarifa;
create policy "tarifa: el dueno borra" on public.tarifa for delete to authenticated
  using ((select privado.rol()) = 'dueno');

drop policy if exists "ordenes: taller y mecanico ven" on public.ordenes;
create policy "ordenes: taller y mecanico ven" on public.ordenes for select to authenticated
  using (
    (select privado.es_taller())
    or ((select privado.rol()) = 'mecanico' and mecanico_id = (select privado.persona()) and estado <> 'entregado')
  );

drop policy if exists "ordenes: taller abre" on public.ordenes;
create policy "ordenes: taller abre" on public.ordenes for insert to authenticated
  with check ((select privado.es_taller()));

drop policy if exists "ordenes: taller y mecanico cambian" on public.ordenes;
create policy "ordenes: taller y mecanico cambian" on public.ordenes for update to authenticated
  using (
    (select privado.es_taller())
    or ((select privado.rol()) = 'mecanico' and mecanico_id = (select privado.persona()) and estado <> 'entregado')
  )
  with check (
    (select privado.es_taller())
    or ((select privado.rol()) = 'mecanico' and mecanico_id = (select privado.persona()) and estado <> 'entregado')
  );

drop policy if exists "conversaciones: taller y asistente (web) ven" on public.conversaciones;
create policy "conversaciones: taller y asistente (web) ven" on public.conversaciones for select to authenticated
  using ((select privado.es_taller()) or ((select privado.rol()) = 'asistente' and canal in ('Web', 'WhatsApp')));

drop policy if exists "conversaciones: el asistente abre chats de la web" on public.conversaciones;
create policy "conversaciones: el asistente abre chats de la web" on public.conversaciones for insert to authenticated
  with check ((select privado.rol()) = 'asistente' and canal in ('Web', 'WhatsApp') and cliente_id is null and not prueba);

drop policy if exists "conversaciones: taller y asistente (web) cambian" on public.conversaciones;
create policy "conversaciones: taller y asistente (web) cambian" on public.conversaciones for update to authenticated
  using ((select privado.es_taller()) or ((select privado.rol()) = 'asistente' and canal in ('Web', 'WhatsApp')))
  with check ((select privado.es_taller()) or ((select privado.rol()) = 'asistente' and canal in ('Web', 'WhatsApp')));

drop policy if exists "mensajes: se ven con su conversacion" on public.mensajes;
create policy "mensajes: se ven con su conversacion" on public.mensajes for select to authenticated
  using (exists (select 1 from public.conversaciones c where c.id = mensajes.conversacion_id));

drop policy if exists "mensajes: taller escribe como persona, asistente como cliente o IA" on public.mensajes;
create policy "mensajes: taller escribe como persona, asistente como cliente o IA" on public.mensajes for insert to authenticated
  with check (
    (((select privado.es_taller()) and de = 'persona') or ((select privado.rol()) = 'asistente' and de in ('cliente', 'ia')))
    and exists (select 1 from public.conversaciones c where c.id = mensajes.conversacion_id)
  );

drop policy if exists "citas: taller ve" on public.citas;
create policy "citas: taller ve" on public.citas for select to authenticated
  using ((select privado.es_taller()));

drop policy if exists "citas: taller y asistente reservan" on public.citas;
create policy "citas: taller y asistente reservan" on public.citas for insert to authenticated
  with check ((select privado.es_taller()) or ((select privado.rol()) = 'asistente' and origen = 'ia' and orden_id is null));

drop policy if exists "citas: taller cambia" on public.citas;
create policy "citas: taller cambia" on public.citas for update to authenticated
  using ((select privado.es_taller())) with check ((select privado.es_taller()));

drop policy if exists "citas: taller anula" on public.citas;
create policy "citas: taller anula" on public.citas for delete to authenticated
  using ((select privado.es_taller()));

-- 6. Triggers y funciones internas
create or replace function privado.proteger_orden() returns trigger
language plpgsql set search_path = '' as $$
declare
  r text := privado.rol();
  n int := jsonb_array_length(old.historial);
begin
  if privado.cargando() then return new; end if;
  if new.id <> old.id then
    raise exception 'No se puede cambiar el código de una orden' using errcode = '42501';
  end if;
  if jsonb_array_length(new.historial) < n
     or (n > 0 and (select jsonb_agg(e order by i) from jsonb_array_elements(new.historial) with ordinality as h(e, i) where i <= n) <> old.historial)
  then
    raise exception 'El historial de una orden no se puede borrar ni cambiar' using errcode = '42501';
  end if;
  if r = 'mecanico' and (
    new.mecanico_id <> old.mecanico_id or new.coche_id <> old.coche_id or new.entrada <> old.entrada
    or new.cierre is distinct from old.cierre or new.estado = 'entregado' or new.informes <> old.informes
  ) then
    raise exception 'Con este perfil no puedes hacer este cambio' using errcode = '42501';
  end if;
  new.version := old.version + 1;
  return new;
end $$;

drop trigger if exists proteger_orden on public.ordenes;
create trigger proteger_orden before update on public.ordenes
  for each row execute function privado.proteger_orden();

create or replace function privado.nueva_orden() returns trigger
language plpgsql set search_path = '' as $$
begin
  if privado.cargando() then return new; end if;
  new.version := 1;
  if privado.rol() <> '' then new.entrada := now(); end if;
  return new;
end $$;

drop trigger if exists nueva_orden on public.ordenes;
create trigger nueva_orden before insert on public.ordenes
  for each row execute function privado.nueva_orden();

create or replace function privado.nuevo_mensaje() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if not privado.cargando() and privado.rol() <> '' then
    new.cuando := now();
    if new.de = 'persona' then
      new.autor := (select p.nombre from public.personas p where p.id = privado.persona());
    else
      new.autor := null;
    end if;
  end if;
  return new;
end $$;

drop trigger if exists nuevo_mensaje on public.mensajes;
create trigger nuevo_mensaje before insert on public.mensajes
  for each row execute function privado.nuevo_mensaje();

create or replace function privado.mensaje_guardado() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  update public.conversaciones set actualizada = greatest(actualizada, new.cuando) where id = new.conversacion_id;
  return null;
end $$;

drop trigger if exists mensaje_guardado on public.mensajes;
create trigger mensaje_guardado after insert on public.mensajes
  for each row execute function privado.mensaje_guardado();

create or replace function privado.nueva_conversacion() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if privado.cargando() then return new; end if;
  if new.canal = 'Web' and btrim(coalesce(new.nombre, '')) = '' then
    new.nombre := 'Visitante web ' || nextval('public.visitante_web');
  elsif new.canal = 'WhatsApp' and btrim(coalesce(new.nombre, '')) = '' then
    new.nombre := coalesce(nullif(btrim(new.contacto), ''), 'Cliente WhatsApp');
  end if;
  if privado.rol() <> '' then
    new.creada := now();
    new.actualizada := now();
  end if;
  return new;
end $$;

drop trigger if exists nueva_conversacion on public.conversaciones;
create trigger nueva_conversacion before insert on public.conversaciones
  for each row execute function privado.nueva_conversacion();

create or replace function privado.proteger_conversacion() returns trigger
language plpgsql set search_path = '' as $$
begin
  if new.id <> old.id or new.canal <> old.canal then
    raise exception 'No se puede cambiar el canal de una conversación' using errcode = '42501';
  end if;
  if privado.rol() = 'asistente' and new.cliente_id is distinct from old.cliente_id then
    raise exception 'El asistente no enlaza clientes' using errcode = '42501';
  end if;
  if new.prueba is distinct from old.prueba and privado.rol() not in ('dueno', '') then
    raise exception 'Solo el dueño marca los chats de prueba' using errcode = '42501';
  end if;
  return new;
end $$;

drop trigger if exists proteger_conversacion on public.conversaciones;
create trigger proteger_conversacion before update on public.conversaciones
  for each row execute function privado.proteger_conversacion();

create or replace function privado.nueva_cita() returns trigger
language plpgsql security definer set search_path = '' as $$
declare
  v_cliente text;
  v_modelo text;
begin
  if privado.cargando() then return new; end if;
  select c.cliente_id, c.modelo into v_cliente, v_modelo
  from public.coches c
  where c.matricula_clave = upper(regexp_replace(new.matricula, '[\s-]', '', 'g'));
  if privado.rol() = 'asistente' or new.cliente_id is null then
    new.cliente_id := v_cliente;
  end if;
  if btrim(coalesce(new.coche, '')) in ('', '—') then
    new.coche := coalesce(v_modelo, '—');
  end if;
  if privado.rol() <> '' then
    new.creada := now();
  end if;
  return new;
end $$;

drop trigger if exists nueva_cita on public.citas;
create trigger nueva_cita before insert on public.citas
  for each row execute function privado.nueva_cita();

-- 7. Funciones invocadas por la API
create or replace function public.asistente_orden(p_codigo text, p_matriculas text[])
returns jsonb
language plpgsql stable security definer set search_path = '' as $$
begin
  if privado.rol() not in ('asistente', 'dueno', 'recepcion') then
    raise exception 'No autorizado' using errcode = '42501';
  end if;
  if coalesce(array_length(p_matriculas, 1), 0) = 0 or array_length(p_matriculas, 1) > 5 then
    return null;
  end if;
  return (
    select jsonb_build_object(
      'id', o.id, 'estado', o.estado, 'km', o.km, 'mecanico_id', o.mecanico_id, 'entrada', o.entrada,
      'cierre', o.cierre, 'motivo', o.motivo, 'trabajos', o.trabajos, 'piezas', o.piezas,
      'coche', jsonb_build_object('matricula', c.matricula, 'modelo', c.modelo)
    )
    from public.ordenes o
    join public.coches c on c.id = o.coche_id
    where o.id = upper(btrim(p_codigo))
      and c.matricula_clave in (select upper(regexp_replace(m, '[\s-]', '', 'g')) from unnest(p_matriculas) as m)
  );
end $$;

create or replace function public.huecos_ocupados(p_desde date, p_hasta date)
returns table (fecha date, hora text)
language plpgsql stable security definer set search_path = '' as $$
begin
  if privado.rol() not in ('asistente', 'dueno', 'recepcion') then
    raise exception 'No autorizado' using errcode = '42501';
  end if;
  if p_hasta < p_desde or p_hasta - p_desde > 92 then
    raise exception 'Rango de fechas no válido' using errcode = '22023';
  end if;
  return query select c.fecha, c.hora from public.citas c where c.fecha between p_desde and p_hasta;
end $$;

create or replace function public.poner_clave(p_persona text, p_clave text)
returns void
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_uid uuid;
begin
  if privado.rol() <> 'dueno' then
    raise exception 'Solo el dueño puede cambiar la contraseña de otra persona' using errcode = '42501';
  end if;
  if p_persona = privado.persona() then
    raise exception 'Tu propia contraseña se cambia desde «Mi contraseña»' using errcode = '22023';
  end if;
  if p_clave is null or char_length(p_clave) < 10 or octet_length(p_clave) > 72 then
    raise exception 'La contraseña tiene que tener entre 10 y 72 caracteres' using errcode = '22023';
  end if;
  select u.id into v_uid from auth.users u
  where u.raw_app_meta_data ->> 'persona' = p_persona
    and u.raw_app_meta_data ->> 'rol' in ('dueno', 'recepcion', 'mecanico');
  if v_uid is null then
    raise exception 'Usuario no encontrado' using errcode = '22023';
  end if;
  update auth.users
  set encrypted_password = extensions.crypt(p_clave, extensions.gen_salt('bf', 10)),
      updated_at = now()
  where id = v_uid;
  delete from auth.sessions where user_id = v_uid;
end $$;

create or replace function public.crear_trabajador(
  p_id text,
  p_nombre text,
  p_nombre_completo text,
  p_rol text,
  p_rol_etiqueta text,
  p_clave text default null
)
returns void
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_uid uuid := gen_random_uuid();
  v_clave text := coalesce(nullif(p_clave, ''), p_id || '-taller-2026');
begin
  if privado.rol() <> 'dueno' then
    raise exception 'Solo el dueño puede dar de alta trabajadores' using errcode = '42501';
  end if;

  p_id := lower(trim(p_id));
  if p_id !~ '^[a-z0-9_-]{2,30}$' then
    raise exception 'El identificador de usuario debe tener entre 2 y 30 caracteres (solo letras minúsculas, números o guiones)' using errcode = '22023';
  end if;

  if p_rol not in ('dueno', 'recepcion', 'mecanico') then
    raise exception 'El rol no es válido' using errcode = '22023';
  end if;

  -- 1. Insertar o actualizar en public.personas
  insert into public.personas (id, nombre, nombre_completo, rol, rol_etiqueta)
  values (p_id, trim(p_nombre), trim(p_nombre_completo), p_rol, trim(p_rol_etiqueta))
  on conflict (id) do update set
    nombre = excluded.nombre,
    nombre_completo = excluded.nombre_completo,
    rol = excluded.rol,
    rol_etiqueta = excluded.rol_etiqueta;

  -- 2. Crear usuario en auth.users si no existe para que pueda iniciar sesión
  if not exists (select 1 from auth.users where email = p_id || '@taller.invalid') then
    if char_length(v_clave) < 10 then
      v_clave := p_id || '-taller-2026';
    end if;

    perform set_config('taller.alta', 'permitida', true);

    insert into auth.users (
      id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
      raw_app_meta_data, raw_user_meta_data, created_at, updated_at
    ) values (
      v_uid, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
      p_id || '@taller.invalid', extensions.crypt(v_clave, extensions.gen_salt('bf', 10)), now(),
      jsonb_build_object('provider', 'email', 'providers', jsonb_build_array('email'), 'persona', p_id, 'rol', p_rol),
      '{}'::jsonb, now(), now()
    );

    insert into auth.identities (id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at)
    values (v_uid, v_uid, json_build_object('sub', v_uid::text, 'email', p_id || '@taller.invalid'), 'email', v_uid::text, now(), now(), now());
  else
    update auth.users
    set raw_app_meta_data = raw_app_meta_data || jsonb_build_object('rol', p_rol, 'persona', p_id),
        updated_at = now()
    where email = p_id || '@taller.invalid';
  end if;
end $$;

create or replace function public.eliminar_trabajador(p_persona text)
returns void
language plpgsql volatile security definer set search_path = '' as $$
declare
  v_uid uuid;
begin
  if privado.rol() <> 'dueno' then
    raise exception 'Solo el dueño puede eliminar trabajadores' using errcode = '42501';
  end if;

  p_persona := lower(trim(p_persona));
  if p_persona = 'paco' or p_persona = privado.persona() then
    raise exception 'No puedes eliminar la cuenta principal del dueño' using errcode = '22023';
  end if;

  -- Comprobar si tiene órdenes activas abiertas en el taller
  if exists (select 1 from public.ordenes where mecanico_id = p_persona and estado <> 'entregado') then
    raise exception 'No se puede eliminar a este mecánico porque tiene órdenes de trabajo abiertas en el taller. Asígnalas a otro mecánico antes de eliminarlo.' using errcode = '22023';
  end if;

  -- Si tiene órdenes entregadas pasadas, reasignarlas a paco para no violar foreign key
  if exists (select 1 from public.ordenes where mecanico_id = p_persona) then
    update public.ordenes set mecanico_id = 'paco' where mecanico_id = p_persona;
  end if;

  -- 1. Eliminar de public.personas
  delete from public.personas where id = p_persona;

  -- 2. Eliminar de auth.users y auth.identities
  select u.id into v_uid from auth.users u where email = p_persona || '@taller.invalid';
  if v_uid is not null then
    delete from auth.identities where user_id = v_uid;
    delete from auth.sessions where user_id = v_uid;
    delete from auth.users where id = v_uid;
  end if;
end $$;

create or replace function privado.cargar_datos(p jsonb)
returns void
language plpgsql volatile security definer set search_path = '' as $$
begin
  perform set_config('taller.cargando', 'si', true);

  insert into public.clientes (id, nombre, nombre_corto, contacto, telefono, email, desde)
  select x.id, x.nombre, x.nombre_corto, x.contacto, x.telefono, x.email, x.desde
  from jsonb_to_recordset(p -> 'clientes') as x (id text, nombre text, nombre_corto text, contacto text, telefono text, email text, desde int);

  insert into public.coches (id, cliente_id, matricula, modelo, anio, combustible)
  select x.id, x.cliente_id, x.matricula, x.modelo, x.anio, x.combustible
  from jsonb_to_recordset(p -> 'coches') as x (id text, cliente_id text, matricula text, modelo text, anio int, combustible text);

  insert into public.tarifa (id, categoria, nombre, tiempo, precio, por_unidad, posicion)
  select x.id, x.categoria, x.nombre, x.tiempo, x.precio, x.por_unidad, t.i
  from jsonb_array_elements(p -> 'tarifa') with ordinality as t (e, i),
       jsonb_to_record(t.e) as x (id text, categoria text, nombre text, tiempo text, precio numeric, por_unidad boolean);
  perform setval(pg_get_serial_sequence('public.tarifa', 'posicion'), greatest((select max(posicion) from public.tarifa), 1));

  insert into public.conversaciones (id, cliente_id, nombre, canal, contacto, modo, necesita_persona, motivo, actualizada, creada)
  select x.id, x.cliente_id, x.nombre, x.canal, x.contacto, x.modo, x.necesita_persona, x.motivo, x.actualizada, x.creada
  from jsonb_to_recordset(p -> 'conversaciones') as x (
    id text, cliente_id text, nombre text, canal text, contacto text, modo text, necesita_persona boolean, motivo text,
    actualizada timestamptz, creada timestamptz
  );

  insert into public.mensajes (id, conversacion_id, de, texto, cuando, autor)
  select x.id, x.conversacion_id, x.de, x.texto, x.cuando, x.autor
  from jsonb_array_elements(p -> 'mensajes') with ordinality as t (e, i),
       jsonb_to_record(t.e) as x (id text, conversacion_id text, de text, texto text, cuando timestamptz, autor text)
  order by t.i;

  insert into public.ordenes (id, coche_id, estado, km, mecanico_id, entrada, cierre, motivo, trabajos, piezas, observaciones, historial, ultima_ia, informes)
  select x.id, x.coche_id, x.estado, x.km, x.mecanico_id, x.entrada, x.cierre, x.motivo,
         x.trabajos, x.piezas, x.observaciones, x.historial, x.ultima_ia, coalesce(x.informes, '{}')
  from jsonb_to_recordset(p -> 'ordenes') as x (
    id text, coche_id text, estado text, km int, mecanico_id text, entrada timestamptz, cierre timestamptz, motivo text,
    trabajos jsonb, piezas jsonb, observaciones jsonb, historial jsonb, ultima_ia jsonb, informes jsonb
  );

  insert into public.citas (id, fecha, hora, nombre, telefono, matricula, coche, motivo, cliente_id, orden_id, conversacion_id, origen, creada)
  select x.id, x.fecha, x.hora, x.nombre, x.telefono, x.matricula, x.coche, x.motivo, x.cliente_id, x.orden_id, x.conversacion_id, x.origen, x.creada
  from jsonb_to_recordset(p -> 'citas') as x (
    id text, fecha date, hora text, nombre text, telefono text, matricula text, coche text, motivo text,
    cliente_id text, orden_id text, conversacion_id text, origen text, creada timestamptz
  );

  perform setval('public.orden_numero', greatest((p ->> 'siguiente_orden')::bigint, 1000), false);
  perform setval('public.visitante_web', greatest(coalesce((p ->> 'visitantes_web')::bigint, 0) + 1, 1), false);

  perform set_config('taller.cargando', '', true);
end $$;

create or replace function public.reiniciar_datos(p_datos jsonb)
returns void
language plpgsql volatile security definer set search_path = '' as $$
begin
  if privado.rol() <> 'dueno' then
    raise exception 'Solo el dueño puede borrar todos los datos' using errcode = '42501';
  end if;
  delete from public.citas where true;
  delete from public.mensajes where true;
  delete from public.conversaciones where true;
  delete from public.ordenes where true;
  delete from public.coches where true;
  delete from public.clientes where true;
  delete from public.tarifa where true;
  perform privado.cargar_datos(p_datos);
end $$;

revoke all on function public.asistente_orden(text, text[]) from public, anon;
grant execute on function public.asistente_orden(text, text[]) to authenticated;

revoke all on function public.huecos_ocupados(date, date) from public, anon;
grant execute on function public.huecos_ocupados(date, date) to authenticated;

revoke all on function public.poner_clave(text, text) from public, anon;
grant execute on function public.poner_clave(text, text) to authenticated;

revoke all on function public.reiniciar_datos(jsonb) from public, anon;
grant execute on function public.reiniciar_datos(jsonb) to authenticated;

revoke all on function privado.cargar_datos(jsonb) from public, anon, authenticated;

-- 8. Población de la tabla personas
insert into public.personas (id, nombre, nombre_completo, rol, rol_etiqueta) values
  ('paco', 'Paco', 'Paco Ruiz', 'dueno', 'Dueño'),
  ('lucia', 'Lucía', 'Lucía Serrano', 'recepcion', 'Recepción'),
  ('javi', 'Javi', 'Javi Martín', 'mecanico', 'Mecánico'),
  ('ruben', 'Rubén', 'Rubén Ortega', 'mecanico', 'Mecánico'),
  ('marta', 'Marta', 'Marta Villalba', 'mecanico', 'Mecánica')
on conflict (id) do update set
  nombre = excluded.nombre,
  nombre_completo = excluded.nombre_completo,
  rol = excluded.rol,
  rol_etiqueta = excluded.rol_etiqueta;

-- 9. Creación de usuarios en auth.users y auth.identities
do $$
declare
  v_paco_id uuid := gen_random_uuid();
  v_lucia_id uuid := gen_random_uuid();
  v_javi_id uuid := gen_random_uuid();
  v_ruben_id uuid := gen_random_uuid();
  v_marta_id uuid := gen_random_uuid();
  v_asistente_id uuid := gen_random_uuid();
begin
  -- Desactivar restricción temporalmente si existe
  perform set_config('taller.alta', 'permitida', true);

  -- 1) Paco (Dueño) -> contraseña: filtro-freno-salpicadero-56
  if not exists (select 1 from auth.users where email = 'paco@taller.invalid') then
    insert into auth.users (
      id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
      raw_app_meta_data, raw_user_meta_data, created_at, updated_at
    ) values (
      v_paco_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
      'paco@taller.invalid', crypt('filtro-freno-salpicadero-56', gen_salt('bf')), now(),
      '{"provider":"email","providers":["email"],"persona":"paco","rol":"dueno"}'::jsonb, '{}'::jsonb, now(), now()
    );

    insert into auth.identities (id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at)
    values (v_paco_id, v_paco_id, json_build_object('sub', v_paco_id::text, 'email', 'paco@taller.invalid'), 'email', v_paco_id::text, now(), now(), now());
  else
    -- Actualizar contraseña y metadata si ya existe
    update auth.users
    set encrypted_password = crypt('filtro-freno-salpicadero-56', gen_salt('bf')),
        raw_app_meta_data = '{"provider":"email","providers":["email"],"persona":"paco","rol":"dueno"}'::jsonb,
        updated_at = now()
    where email = 'paco@taller.invalid';
  end if;

  -- 2) Lucía (Recepción) -> contraseña: recepcion-ruiz-2026
  if not exists (select 1 from auth.users where email = 'lucia@taller.invalid') then
    insert into auth.users (
      id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
      raw_app_meta_data, raw_user_meta_data, created_at, updated_at
    ) values (
      v_lucia_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
      'lucia@taller.invalid', crypt('recepcion-ruiz-2026', gen_salt('bf')), now(),
      '{"provider":"email","providers":["email"],"persona":"lucia","rol":"recepcion"}'::jsonb, '{}'::jsonb, now(), now()
    );

    insert into auth.identities (id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at)
    values (v_lucia_id, v_lucia_id, json_build_object('sub', v_lucia_id::text, 'email', 'lucia@taller.invalid'), 'email', v_lucia_id::text, now(), now(), now());
  end if;

  -- 3) Javi (Mecánico) -> contraseña: mecanico-javi-2026
  if not exists (select 1 from auth.users where email = 'javi@taller.invalid') then
    insert into auth.users (
      id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
      raw_app_meta_data, raw_user_meta_data, created_at, updated_at
    ) values (
      v_javi_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
      'javi@taller.invalid', crypt('mecanico-javi-2026', gen_salt('bf')), now(),
      '{"provider":"email","providers":["email"],"persona":"javi","rol":"mecanico"}'::jsonb, '{}'::jsonb, now(), now()
    );

    insert into auth.identities (id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at)
    values (v_javi_id, v_javi_id, json_build_object('sub', v_javi_id::text, 'email', 'javi@taller.invalid'), 'email', v_javi_id::text, now(), now(), now());
  end if;

  -- 4) Rubén (Mecánico) -> contraseña: mecanico-ruben-2026
  if not exists (select 1 from auth.users where email = 'ruben@taller.invalid') then
    insert into auth.users (
      id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
      raw_app_meta_data, raw_user_meta_data, created_at, updated_at
    ) values (
      v_ruben_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
      'ruben@taller.invalid', crypt('mecanico-ruben-2026', gen_salt('bf')), now(),
      '{"provider":"email","providers":["email"],"persona":"ruben","rol":"mecanico"}'::jsonb, '{}'::jsonb, now(), now()
    );

    insert into auth.identities (id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at)
    values (v_ruben_id, v_ruben_id, json_build_object('sub', v_ruben_id::text, 'email', 'ruben@taller.invalid'), 'email', v_ruben_id::text, now(), now(), now());
  end if;

  -- 5) Marta (Mecánica) -> contraseña: mecanica-marta-2026
  if not exists (select 1 from auth.users where email = 'marta@taller.invalid') then
    insert into auth.users (
      id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
      raw_app_meta_data, raw_user_meta_data, created_at, updated_at
    ) values (
      v_marta_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
      'marta@taller.invalid', crypt('mecanica-marta-2026', gen_salt('bf')), now(),
      '{"provider":"email","providers":["email"],"persona":"marta","rol":"mecanico"}'::jsonb, '{}'::jsonb, now(), now()
    );

    insert into auth.identities (id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at)
    values (v_marta_id, v_marta_id, json_build_object('sub', v_marta_id::text, 'email', 'marta@taller.invalid'), 'email', v_marta_id::text, now(), now(), now());
  end if;

  -- 6) Asistente (Bot chat público) -> contraseña: asistente-ruiz-clave-secreta-2026
  if not exists (select 1 from auth.users where email = 'asistente@taller.invalid') then
    insert into auth.users (
      id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
      raw_app_meta_data, raw_user_meta_data, created_at, updated_at
    ) values (
      v_asistente_id, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated',
      'asistente@taller.invalid', crypt('asistente-ruiz-clave-secreta-2026', gen_salt('bf')), now(),
      '{"provider":"email","providers":["email"],"rol":"asistente"}'::jsonb, '{}'::jsonb, now(), now()
    );

    insert into auth.identities (id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at)
    values (v_asistente_id, v_asistente_id, json_build_object('sub', v_asistente_id::text, 'email', 'asistente@taller.invalid'), 'email', v_asistente_id::text, now(), now(), now());
  end if;

  -- Inicializar campos de token en '' para compatibilidad con Supabase GoTrue
  update auth.users
  set confirmation_token = coalesce(confirmation_token, ''),
      recovery_token = coalesce(recovery_token, ''),
      email_change_token_new = coalesce(email_change_token_new, ''),
      email_change = coalesce(email_change, ''),
      email_change_token_current = coalesce(email_change_token_current, ''),
      phone_change = coalesce(phone_change, ''),
      phone_change_token = coalesce(phone_change_token, ''),
      reauthentication_token = coalesce(reauthentication_token, '');
end $$;

-- 10. Bloquear altas externas en auth.users
create or replace function privado.bloquear_altas() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if coalesce(current_setting('taller.alta', true), '') <> 'permitida' then
    raise exception 'Las altas de usuarios están cerradas' using errcode = '42501';
  end if;
  return new;
end $$;
revoke all on function privado.bloquear_altas() from public, anon, authenticated;

drop trigger if exists bloquear_altas on auth.users;
create trigger bloquear_altas before insert on auth.users
  for each row execute function privado.bloquear_altas();

-- =============================================================================
-- Fin del script. Ahora ejecuta 'npm run reset' para poblar los datos de prueba.
-- =============================================================================
